# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maidenName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
