# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AptNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='addressfile',
            name='aptFiles',
            field=models.ManyToManyField(blank=True, to='addressApp.AptNum'),
        ),
    ]
