# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressfile',
            name='aptFiles',
        ),
        migrations.AddField(
            model_name='addressfile',
            name='aptNums',
            field=models.ManyToManyField(to='addressApp.AptNum', verbose_name='list of apartment numbers'),
        ),
    ]
